import { Event } from "@/database";
import connectDB from "@/lib/mongodb";
import { NextRequest, NextResponse } from "next/server";

interface RouteContext {
  params: Promise<{ slug: string }>;
}

interface ErrorResponse {
  message: string;
}

/** Matches URL-safe slugs generated by the Event model. */
const SLUG_PATTERN = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;

function parseSlug(rawSlug: string | undefined): string | null {
  if (!rawSlug?.trim()) {
    return null;
  }

  const slug = decodeURIComponent(rawSlug).trim().toLowerCase();

  if (!SLUG_PATTERN.test(slug)) {
    return null;
  }

  return slug;
}

export async function GET(
  _request: NextRequest,
  context: RouteContext,
): Promise<NextResponse> {
  try {
    const { slug: rawSlug } = await context.params;
    const slug = parseSlug(rawSlug);

    if (!slug) {
      return NextResponse.json<ErrorResponse>(
        { message: "Invalid or missing slug parameter" },
        { status: 400 },
      );
    }

    await connectDB();

    const event = await Event.findOne({ slug });

    if (!event) {
      return NextResponse.json<ErrorResponse>(
        { message: "Event not found" },
        { status: 404 },
      );
    }

    return NextResponse.json({ event }, { status: 200 });
  } catch (error) {
    console.error("GET /api/events/[slug] error:", error);

    return NextResponse.json<ErrorResponse>(
      { message: "Failed to fetch event" },
      { status: 500 },
    );
  }
}
